name: ModSuite
main: gg.maiko.modsuite.ModSuite
author: MaikoX
version: 1.0
commands:
  staffmode:
    aliases:
      - sm
      - modmode
      - mm
      - h
      - staff
      - mod
      - modsuite
  freeze:
    aliases:
      - screenshare
      - ss
  unfreeze:
    aliases:
      - unss
  vanish:
    aliases:
      - v
      - invisible
      - invis